# default

path=(
	$HOME/bin
	/Applications/bin
	/usr/local/bin
	/usr/local/sbin
	/usr/bin
	/usr/sbin
	/bin
	/sbin
	/usr/X11/bin

	$PATH

	$HOME/.rbenv/bin
)

if [[ $HOST =~ '^lizak' ]]; then
	path=(
		/usr/local/zsh/bin # where my custom zsh lives
		/opt/local/bin     # macports
		/opt/local/sbin    # macports
		/sw/bin            # fink
		/Applications/MacVim.app/Contents/MacOS
		$HOME/perl5/perlbrew/etc/cshrc

		$PATH
	)
fi

#export http_proxy=http://10.101.1.155:3128
export PATH
export EDITOR=vim

eval "$(rbenv init -)"

[[ -s ~/perl5/perlbrew/etc/bashrc ]] && source ~/perl5/perlbrew/etc/bashrc

eval $(keychain --eval --agents ssh -Q --quiet id_dsa_snowman id_rsa_git_gitlab_venda id_rsa_git_venda id_rsa)

